### ISSUE TITLE
特来star，顺便建议添加实时估值走势图

### ISSUE THREAD

**Issue by ApacheRen** [x2rr/funds#11]
是否可以单击选中一只基金后，左边再把当天的估值走势显示出来呢。
像下图这种。

![image](https://user-images.githubusercontent.com/33214126/87748665-1a60fe80-c829-11ea-9cca-5060b2209a31.png)

**Comment by x2rr** [comment]
> 是否可以单击选中一只基金后，左边再把当天的估值走势显示出来呢。
> 像下图这种。
> 
> ![image](https://user-images.githubusercontent.com/33214126/87748665-1a60fe80-c829-11ea-9cca-5060b2209a31.png)

新版本v1.8.0已支持

**Comment by ApacheRen** [comment]
给大佬点赞👍👍
