### ISSUE TITLE
设置中关闭“显示持有收益”后编辑对话框中错位

### ISSUE THREAD

**Issue by deplives** [x2rr/funds#114]
![image](https://user-images.githubusercontent.com/53208952/106419938-94d73000-6494-11eb-920e-38fcdad8521b.png)

**Comment by x2rr** [comment]
请升级最新版

**Comment by deplives** [comment]
请问 v2.4.2 是不是最新版呢？如果不是怎么获取最新版？

**Comment by x2rr** [comment]
> 请问 v2.4.2 是不是最新版呢？如果不是怎么获取最新版？

该问题为历史问题，最新版为v2.4.2,已解决。[下载地址](https://rabt.gitee.io/funds/docs/dist/index.html#/Download)

**Comment by deplives** [comment]
![image](https://user-images.githubusercontent.com/53208952/106433118-b0e5cc00-64aa-11eb-9c9b-0b0975dce220.png)
![image](https://user-images.githubusercontent.com/53208952/106433128-b4795300-64aa-11eb-9ee2-2541edbdc4e6.png)

**Comment by x2rr** [comment]
额。。。确实，下版本解决
