### ISSUE TITLE
港基出现的bug  涨幅为正  但是显示预估收益为负

### ISSUE THREAD

**Issue by 17764591637** [x2rr/funds#115]
![image](https://user-images.githubusercontent.com/38268685/106567540-f66acd80-656c-11eb-979e-f5a87fa4089a.png)

**Comment by kfqkfy** [comment]
这个是天天那边的bug，天天是基于早上9点半之前的净值，然后估算当天的增长率，算当天的估值，等到下午净值更新了，如果当天的估值比更新后的净值还低，那就绿了，这个得天天那边更新修复

**Comment by x2rr** [comment]
一般为基金产生分红导致的净值下降，估算收益数值为当天实际收益减去分红金额后的金额。
