### ISSUE TITLE
firefox提示 自选基金助手 - 实时查看基金涨跌幅 由于安全或稳定性问题已被禁用。

### ISSUE THREAD

**Issue by jq384044342** [x2rr/funds#125]
老哥，这个能解决下吗，我禁用了安全检查还是不能使用，感谢

**Comment by x2rr** [comment]
Firefox因为审核被驳回（奇葩，之前已审核通过的版本又被驳回），导致暂时被下架，请暂时更换其他浏览器或者等待新版本上架

**Comment by jq384044342** [comment]
> 
> 
> Firefox因为审核被驳回（奇葩，之前已审核通过的版本又被驳回），导致暂时被下架，请暂时更换其他浏览器或者等待新版本上架

好的，感谢！先暂时有chrome了，主要是增加了好多基金。有考虑过增加登录同步已添加基金的功能吗？

**Comment by x2rr** [comment]
3.0.2最新版已支持

**Comment by jq384044342** [comment]
> 
> 
> 3.0.2最新版已支持

老哥牛逼！

**Comment by x2rr** [comment]
重新上架了，欢迎使用，欢迎评论、评分
[https://addons.mozilla.org/zh-CN/firefox/addon/funds/](url)

**Comment by KCCat** [comment]
再次被下架

**Comment by WPSG** [comment]
又被下架了。
![image](https://user-images.githubusercontent.com/34449596/110732100-77993c80-825e-11eb-91ae-a91b605199eb.png)

**Comment by jq384044342** [comment]
> 
> 
> 重新上架了，欢迎使用，欢迎评论、评分
> [https://addons.mozilla.org/zh-CN/firefox/addon/funds/](url)

老哥，还是下架了，是违反firefox的哪些规则了吗？还是被举报了，看着提示不像是被举报

**Comment by x2rr** [comment]
可能是因为导出Excel功能，已经去掉并重新提交审核了

**Comment by jq384044342** [comment]
> 
> 
> 可能是因为导出Excel功能，已经去掉并重新提交审核了

老哥，firefox是不是以后都用不了了[\沮丧]
