### ISSUE TITLE
日志中：修复基金持有收益率计算问题

### ISSUE THREAD

**Issue by xionghaizhi** [x2rr/funds#126]
请问这个代码没上传吗？我用之前的代码算出来的和最新版插件算出来的是一致的。代码中也没见修改哪里的计算呀

**Comment by x2rr** [comment]
下方的总持有收益率

**Comment by xionghaizhi** [comment]
![image](https://user-images.githubusercontent.com/30396478/108939479-bccd4400-768c-11eb-8056-68e51a4424a6.png)
这个吗？这个显示还是updatev2.4.0时的

**Comment by xionghaizhi** [comment]
> 下方的总持有收益率

![image](https://user-images.githubusercontent.com/30396478/108939706-12a1ec00-768d-11eb-8316-252906cc9946.png)
这个吗？git日志显示还是updatev2.4.0时的

**Comment by xionghaizhi** [comment]
> 下方的总持有收益率

能把账号相关的代码去掉，提交一版最新计算方式的代码吗？我现在二次开发的金额和比率和插件的信息对不起来了，感谢

**Comment by x2rr** [comment]
已提交，代码如下，由 总收益/总金额 改为 总收益/(总金额-总收益)
```js
allCostGains() {
      let allCostGains = 0;
      let allNum = 0;
      this.dataList.forEach((val) => {
        allCostGains += parseFloat(val.costGains);
        allNum += parseFloat(val.amount);
      });
      allCostGains = allCostGains.toFixed(2);
      let allCostGainsRate = (
        (allCostGains * 100) /
        (allNum - allCostGains)
      ).toFixed(2);
      return [allCostGains, allCostGainsRate];
    }
```
