### ISSUE TITLE
想问作者接受pr嘛？

### ISSUE THREAD

**Issue by misterchaos** [x2rr/funds#13]
作者大大：
   我最近在找一个能摸鱼看行情的插件所以发现了这个，用起来感觉很棒！
   我想参与这个项目把它做得更好：
        做个简单的登录注册，可以保存基金代码，持有份额等信息。
   PS：我可以帮忙写后端代码并提供服务器，有意的话可以邮件联系我鸭！
   Contact：misterchaos@163.com

Yuchao Huang

**Comment by x2rr** [comment]
目前支持跟随浏览器账户同步，以及导入导入配置，暂时不考虑注册登录功能
