### ISSUE TITLE
账号同步的源码没提交到github

### ISSUE THREAD

**Issue by taxilng** [x2rr/funds#131]

**Comment by taxilng** [comment]
github的源码还停留在2.5.2版本，请问下作者代码是在哪里维护的？github，gitee，gitlab？

**Comment by xionghaizhi** [comment]
> github的源码还停留在2.5.2版本，请问下作者代码是在哪里维护的？github，gitee，gitlab？

gitee上也是2.5.2，只更新了日志文件

**Comment by x2rr** [comment]
新版本涉及到了账号服务，为确保服务安全性，暂时不提交服务相关源码
