### ISSUE TITLE
自定义手续费

### ISSUE THREAD

**Issue by deplives** [x2rr/funds#132]
在基金公司官方买的手续费可能为0，在银行买的可能为1.5 在天天等买的可能为0.15，希望能自定义手续费比例

**Comment by qqizai** [comment]
哈哈哈哈，过分了，你这要求

**Comment by deplives** [comment]
> 哈哈哈哈，过分了，你这要求

前几天接连在基金公司 0% 加仓，结果现在两边的金额已经对不上了，差了小1k了

**Comment by x2rr** [comment]
默认手续费一般都是正确的，手动修改的话直接编辑就行呀
