### ISSUE TITLE
代码怎么跑起来？

### ISSUE THREAD

**Issue by zhouxiangxian** [x2rr/funds#133]
怎么运行起来呢？

**Comment by x2rr** [comment]
需要node环境，执行
`npm i`
安装依赖，然后
`npm run build`
生成dist文件夹，浏览器加载即可

**Comment by zhouxiangxian** [comment]
生成了dist 目录，没占端口运行麽？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x2rr/funds"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午5:28
收件人:&nbsp;"x2rr/funds"<funds@noreply.github.com&gt;;
抄送:&nbsp;"小贤"<203492752@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [x2rr/funds] 代码怎么跑起来？ (#133)





 
需要node环境，执行
 npm i
 安装依赖，然后
 npm run build
 生成dist文件夹，浏览器加载即可

**Comment by zhouxiangxian** [comment]
必须得打包之后在丢到容器里面才可以访问麽？能不能启动之后可以调试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x2rr/funds"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午5:28
收件人:&nbsp;"x2rr/funds"<funds@noreply.github.com&gt;;
抄送:&nbsp;"小贤"<203492752@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [x2rr/funds] 代码怎么跑起来？ (#133)





 
需要node环境，执行
 npm i
 安装依赖，然后
 npm run build
 生成dist文件夹，浏览器加载即可

**Comment by x2rr** [comment]
开发调试模式执行
`npm run watch:dev`

**Comment by zhouxiangxian** [comment]
开发调试模式执行
npm run watch:dev&nbsp; 执行之后怎么看执行的效果，全局搜索了一下port,没发现端口；能像那种web程序一样输入开发调试地址进行预览不




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "x2rr/funds"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午5:44
收件人:&nbsp;"x2rr/funds"<funds@noreply.github.com&gt;;
抄送:&nbsp;"小贤"<203492752@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [x2rr/funds] 代码怎么跑起来？ (#133)





 
开发调试模式执行
 npm run watch:dev
