### ISSUE TITLE
插件角标百分比显示BUG

### ISSUE THREAD

**Issue by lyp039078** [x2rr/funds#140]
点击前角标显示的收益百分比时正常的，但点开后就变了，与实际不一致
Edge的插件

![image](https://user-images.githubusercontent.com/50280030/113261043-8b860a80-9301-11eb-861d-79bf38283403.png)

**Comment by x2rr** [comment]
最新版3.0.3已解决这个问题，请手动安装最新版或者耐心等待商店更新。
