### ISSUE TITLE
1.无法添加基金2.第二个显示屏无法点击添加新基金按钮

### ISSUE THREAD

**Issue by hanyce** [x2rr/funds#15]
![image](https://user-images.githubusercontent.com/37854396/87896294-5fc83a80-ca7a-11ea-9114-580172d6e1ea.png)
![image](https://user-images.githubusercontent.com/37854396/87896313-6e165680-ca7a-11ea-8dbd-8387be13e43b.png)

**Comment by hanyce** [comment]
网络原因

**Comment by BosenY** [comment]
Same problem as you.
