### ISSUE TITLE
请问为什么角标这里的百分比和面板里的日收益率不一致？

### ISSUE THREAD

**Issue by alexcdever** [x2rr/funds#155]
角标：
![image](https://user-images.githubusercontent.com/14200813/120279192-be8c5080-c2e8-11eb-9cbe-78a2294c4cbc.png)
面板里的收益率：
![image](https://user-images.githubusercontent.com/14200813/120279230-c815b880-c2e8-11eb-9bbd-9542496dc34d.png)
设置：
![image](https://user-images.githubusercontent.com/14200813/120279294-d7950180-c2e8-11eb-8108-8c598b727f59.png)

现在在用的浏览器：
版本 91.0.864.37 (官方内部版本) (64 位)
Microsoft Edge 更新由你的组织管理。

**Comment by x2rr** [comment]
升级最新版解决
