### ISSUE TITLE
数据全部丢失了，界面一片空白

### ISSUE THREAD

**Issue by perpetually** [x2rr/funds#176]
是服务器出bug了么？
![Snipaste_2021-10-09_15-57-47](https://user-images.githubusercontent.com/39957226/136649702-19b3f528-4a77-456c-8321-72fb6ced57e3.jpg)

**Comment by x2rr** [comment]
一般为本机网络问题

**Comment by perpetually** [comment]
> 能否提供一下当前的基金列表？可以在设置中导出

我重新安装了一下，并没有解决这个问题，我本地网络良好，刷新了很多次都是这样的

**Comment by perpetually** [comment]
> 试试在浏览器上能否打开此链接并正常返回数据。 [链接](https://fundmobapi.eastmoney.com/FundMNewApi/FundMNFInfo?pageIndex=1&pageSize=200&plat=Android&appType=ttjj&product=EFund&Version=1&deviceid=230874bd-c234-4e40-84f1-6a1a05fad7fb&Fcodes=007531)

![image](https://user-images.githubusercontent.com/39957226/136655325-45f0d4c7-eb2e-4808-8768-945fb2becc56.png)

**Comment by CaoShenZhou** [comment]
我也是

**Comment by yyx3658** [comment]
确实挂了，导入备份和从云端下载数据都是空白。。。

**Comment by gebiWangshushu** [comment]
一样自选基金全没了，一片空白

**Comment by cauchyguo** [comment]
挂了啊兄弟，全是空的。在编辑里面按代码也搜不到之前添加的基金信息。

**Comment by cauchyguo** [comment]
> 目前我这里是正常的，根据大家的反馈，某些浏览器会提示网络繁忙，某些又没问题，初步判断为数据源屏蔽了某些浏览器的请求

我这用的chrome浏览器，版本 94.0.4606.81

**Comment by kuole-o** [comment]
俺也这样

**Comment by zs492761271** [comment]
同样的情况，该这么处理呀。

**Comment by m511386374** [comment]
我也出现了这个问题

**Comment by Yinwenxu** [comment]
我的也出问题了

**Comment by wangyi404** [comment]
接口崩了 看一看

**Comment by ybjecho** [comment]
接口崩了，
![image](https://user-images.githubusercontent.com/35158427/136726548-63ecb2f5-f11b-4a9a-b9ad-efa6871aada5.png)

**Comment by perpetually** [comment]
最新的3.04作者已经修复了，大家快点更新，感谢大佬

**Comment by KeZhimin** [comment]
应该是headers里面User-Agent的value有问题，默认直接请求value是``Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38``，把value中``AppleWebKit/537.36 (KHTML, like Gecko)``这个去掉就可以了。

**Comment by xuyh1024** [comment]
> 应该是headers里面User-Agent的value有问题，默认直接请求value是`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38`，把value中`AppleWebKit/537.36 (KHTML, like Gecko)`这个去掉就可以了。

**确实，排查了半天错误，但是直接在请求里添加是不行的**
### 尝试在 background.js 中添加如下代码
``` javascript
chrome.webRequest.onBeforeSendHeaders.addListener(
    function(details) {
      details.requestHeaders.push({name: 'User-Agent', value: 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/94.0.4606.71'});
      return {requestHeaders: details.requestHeaders};
    },
    {urls: ['<all_urls>']},
    ['blocking', 'requestHeaders']
);

```
