### ISSUE TITLE
数据能同步 但是面板不显示 小程序正常

### ISSUE THREAD

**Issue by Breathe97** [x2rr/funds#178]
数据能同步 但是面板不显示 小程序正常，正常添加基金也不行 添加成功但是面板一个不显示

**Comment by x2rr** [comment]
3.0.4版本已修复，试一下 [choose-funds-v3.0.4.crx](https://github.com/x2rr/funds/releases/download/3.0.4/choose-funds-v3.0.4.crx)

**Comment by perpetually** [comment]
可以的，这个版本正常了，感谢大佬
