### ISSUE TITLE
涨跌幅的值不准确，与支付宝的值不一样

### ISSUE THREAD

**Issue by Huomen** [x2rr/funds#18]
老哥能否优化一下 感谢

**Comment by blackzhy** [comment]
支付宝也是预估的，准确率也就那样吧，基金本来的仓位就不会完全公布，而且经理如果频繁调仓，值就可能不太对。这个插件用的是天天基金网的估值数据。

**Comment by leytou** [comment]
这个是从天天基金的api获取的，我个人觉得天天基金的预估值比支付宝的更准确
