### ISSUE TITLE
收益显示错误

### ISSUE THREAD

**Issue by HKmylove** [x2rr/funds#188]
![image](https://user-images.githubusercontent.com/45782901/145324348-c3634e24-d47d-4fc0-9192-48b96910cd2b.png)
涨幅是1.73% 预估收益却是负的

**Comment by qq564567484** [comment]
+1 , 涨跌幅是正0.01，预估收益 -1300,这种错误不应该啊

**Comment by x2rr** [comment]
这种是分红了，估算收益为：当日收益金额-分红金额

**Comment by qq564567484** [comment]
原来如此
