### ISSUE TITLE
图标提示的底色过于刺眼 

### ISSUE THREAD

**Issue by jony4** [x2rr/funds#203]
<img width="44" alt="image" src="https://user-images.githubusercontent.com/13718575/173973499-dcdac172-35a8-497f-b957-1a1bd9b2a847.png">

之前是数字红色，现在变成了底色红色，数字黑色，太刺眼而且也不能直观看清数字，能改回之前的样式吗？

**Comment by pengluday** [comment]
您的邮件已收到。
