### ISSUE TITLE
小程序和插件都打不开了一直转圈圈

### ISSUE THREAD

**Issue by perpetually** [x2rr/funds#220]
![image](https://github.com/x2rr/funds/assets/39957226/f7e4d5a8-58c0-4dcf-8cfa-e4de87a578b6)

![32a7b81389bc1bc383ab9e9857ec20c](https://github.com/x2rr/funds/assets/39957226/cb5feff1-f634-4fca-a16a-d6f89fc940ca)

**Comment by 17764591637** [comment]
一样的问题

**Comment by perpetually** [comment]
期待尽快解决

**Comment by FDU-YSP** [comment]
同遇到加载转圈问题，感谢大佬抓紧修复

**Comment by perpetually** [comment]
![image](https://github.com/x2rr/funds/assets/39957226/7b773dcd-b8cc-40d8-8f63-9f30e2d68089)

普通的基金有数据了，但是纳斯达克，标普500这种QDII基金还是没有数字

**Comment by ZJJ955** [comment]
我也遇到了
