### ISSUE TITLE
3.0.5基金添加不上

### ISSUE THREAD

**Issue by vvanglro** [x2rr/funds#223]

**Comment by x2rr** [comment]
请提供详细信息

**Comment by vvanglro** [comment]
https://github.com/x2rr/funds/assets/43594924/76316bd9-0161-4d86-a0c7-bb27c2f6542c

**Comment by x2rr** [comment]
已添加的基金中可能存在异常或错误基金代码，导致报错，可在设置中导出后查看

**Comment by vvanglro** [comment]
我是卸载完全重装过插件的, 貌似搜索出来的任何基金都无法添加.

**Comment by x2rr** [comment]
先删除这条，这条基金已经无法请求到数据，导致报错
`{
		"code": "968061",
		"num": 0
	},`
