### ISSUE TITLE
基金估值功能估计要成历史了，让我们拭目以待

### ISSUE THREAD

**Issue by x2rr** [x2rr/funds#225]

**Comment by acteds** [comment]
如果股票软件也没了,用前十大重仓股简单拟合一下也是可以的.

**Comment by FDU-YSP** [comment]
以后不能看实时价格了？那岂不是割韭菜更简单了

**Comment by FDU-YSP** [comment]
如果这个插件也不能看了，那我就准备卖掉全部基金了

**Comment by taozuidesongshu** [comment]
我排查了一下，插件是调用的同花顺的接口，然后所有基金信息接口都返回null，若是接口提供方关闭了实时价格数据，那就GG了
