### ISSUE TITLE
基金助手又无限转圈圈，是不是接口出问题了

### ISSUE THREAD

**Issue by shenhui0929** [x2rr/funds#234]
基金助手又无限转圈圈，是不是接口出问题了

**Comment by cjy1998** [comment]
+1

**Comment by x2rr** [comment]
插件改dns解析地址了，具体生效时间与各地dns服务器有关，可尝试清除缓存
（原基金数据不支持跨域，所以用服务器做了中转，服务器为有效期90天的gcp，所以需要定期修改dns解析）

**Comment by lucky-wh** [comment]
具体怎么操作呢？

**Comment by cjy1998** [comment]
> 具体怎么操作呢？

打开浏览器的设置，然后清除一下缓存就好了

**Comment by yy4020** [comment]
> > 具体怎么操作呢？
> 
> 打开浏览器的设置，然后清除一下缓存就好了

666 果然清下缓存就好了~

**Comment by HerbLuo** [comment]
真的可以了哇

**Comment by ShinChven** [comment]
能不能把服务端到cloudflare?然后用户可以自行配置后端。

**Comment by ShinChven** [comment]
popup.html:1 Access to XMLHttpRequest at 'https://fund.rabt.top/api/js/012620.js' (redirected from 'http://fund.rabt.top/api/js/012620.js') from origin 'chrome-extension://dhdelcemeednchdmijiocipbjlknndff' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


你请写的服务有跨域的问题吧

**Comment by HerbLuo** [comment]
> popup.html:1 Access to XMLHttpRequest at 'https://fund.rabt.top/api/js/012620.js' (redirected from 'http://fund.rabt.top/api/js/012620.js') from origin 'chrome-extension://dhdelcemeednchdmijiocipbjlknndff' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> 新写的服务有跨域的问题

好像Chrome插件本来就可以直接绕过跨域这个问题的

**Comment by HerbLuo** [comment]
<img width="664" alt="image" src="https://github.com/x2rr/funds/assets/19686958/af1388e4-c309-4cc0-9308-2ad536f49e29">
