### ISSUE TITLE
更新3.2后无法添加基金

### ISSUE THREAD

**Issue by Guovin** [x2rr/funds#235]
更新后列表空了，编辑搜索添加后也没有同步到列表中，再次搜索也查不到该基金

**Comment by pengluday** [comment]
您的邮件已收到。

**Comment by x2rr** [comment]
Manifest V3版本权限有调整，请允许权限；
部分基金能搜到，但数据源无估值提供，已过滤，所以添加后不显示。

**Comment by Guovin** [comment]
> Manifest V3版本权限有调整，请允许权限； 部分基金能搜到，但数据源无估值提供，已过滤，所以添加后不显示。

@x2rr 上版161725、160632是可以提供估值的，新版没了？

**Comment by x2rr** [comment]
> > Manifest V3版本权限有调整，请允许权限； 部分基金能搜到，但数据源无估值提供，已过滤，所以添加后不显示。
> 
> @x2rr 上版161725、160632是可以提供估值的，新版没了？

经测试，以上两个基金正常，请检查自身浏览器版本、网络、权限设置等问题。

**Comment by Guovin** [comment]
> > > Manifest V3版本权限有调整，请允许权限； 部分基金能搜到，但数据源无估值提供，已过滤，所以添加后不显示。
> > 
> > 
> > @x2rr 上版161725、160632是可以提供估值的，新版没了？
> 
> 经测试，以上两个基金正常，请检查自身浏览器版本、网络、权限设置等问题。

浏览器chrome 120.0.6099.130，添加后要设置什么特殊的权限吗？

**Comment by jsony** [comment]
同样，老版本一直在转圈，更新3.2后列表空了，编辑搜索添加后也没有同步到列表中，再次搜索也查不到该基金

**Comment by x2rr** [comment]
更新3.2.1解决
