### ISSUE TITLE
阅读你的浏览历史记录，这个权限有必要吗

### ISSUE THREAD

**Issue by LitchiCherry** [x2rr/funds#237]
之前的版本是不需要这个权限的吧

**Comment by x2rr** [comment]
使用tabs权限就会出现提示，有弹出页面功能、在标签页打开扩展页面的扩展程序，都需要这个权限
<img width="1338" alt="image" src="https://github.com/x2rr/funds/assets/23189213/1ac64eaa-bb37-4eb9-b895-2354fd9a04d3">
<img width="834" alt="image" src="https://github.com/x2rr/funds/assets/23189213/741a7fff-ed0f-4d09-a1ca-d8077a566990">
