### ISSUE TITLE
请求公布最新的Manifest V3代码

### ISSUE THREAD

**Issue by zkl2333** [x2rr/funds#239]
你好，

我在微信群中关注到了关于贵插件权限增加的讨论，尤其是与Manifest V3更新相关的部分。一些用户对新权限，特别是chrome.tabs API可能访问浏览历史记录的情况表示担心。

虽然您在评论区解释了这是Manifest V3升级的结果，但仍有用户对此表示怀疑，担心可能会滥用历史记录。

由于这个插件是开源的，我试图通过审查代码来了解具体情况。但我发现GitHub仓库中并未发布与Manifest V3更新相关的最新代码，仅有的是changeLog的更新。

为了解除社区的疑虑，并提升透明度，恳请您能够尽快在GitHub上公布与Manifest V3相关的最新代码。这将使得社区成员能够自行查看和验证这些更改。

感谢您的理解和支持。

**Comment by jsony** [comment]
有微信群吗 拉我一下 yangyao8

**Comment by x2rr** [comment]
已排查并找出问题，3.2.3已删除无关权限。

鉴于1、已出现多个基于本项目开发的第三方未遵循开源协议并以此盈利。2、已加入账号登录、数据同步功能。
后续版本不再开源
