### ISSUE TITLE
一直搜索不到501018，天天基金是有数据的

### ISSUE THREAD

**Issue by LLawlight** [x2rr/funds#26]
![image](https://user-images.githubusercontent.com/17525377/89251210-0c90e300-d649-11ea-92f3-0fd967d9e131.png)
![image](https://user-images.githubusercontent.com/17525377/89251252-1dd9ef80-d649-11ea-9c1e-d1eea37d02b3.png)

**Comment by icepole-jon** [comment]
该基金暂停销售了，没有估值，接口请求不到数据的
