### ISSUE TITLE
优化下滚动条

### ISSUE THREAD

**Issue by mzzhref** [x2rr/funds#3]
加入基金过多的话会有滚动条，个人感觉很难看

哈哈哈，不影响使用，为作者点赞

**Comment by x2rr** [comment]
> 加入基金过多的话会有滚动条，个人感觉很难看
> 
> 哈哈哈，不影响使用，为作者点赞

chrome扩展的最大高度限制是600px，优化的话只能考虑减小行间距了

**Comment by mzzhref** [comment]
这样啊，我没考虑到，哈哈哈，那可以把滚动条优化下，改成：https://www.cnblogs.com/web-aqin/p/11244121.html

做的很好，我已经在我同学那推荐用了好几个了
