### ISSUE TITLE
昨天突然很多添加的基金丢失了,也无法统计金额了

### ISSUE THREAD

**Issue by CaoShenZhou** [x2rr/funds#31]
出啥事儿

**Comment by yi-Xu-0100** [comment]
我这好像也是，以前添加的都没了，就剩一个了，不知道为啥？

**Comment by CaoShenZhou** [comment]
> 我这好像也是，以前添加的都没了，就剩一个了，不知道为啥？

😂奇了怪

**Comment by yi-Xu-0100** [comment]
如果支持导入导出就好了~ #17

**Comment by RiTian96** [comment]
我的也是

**Comment by javaygq** [comment]
作者赶紧出来解决一下，有bug了

**Comment by SimonYHB** [comment]
希望能解决下，不然添加了下次又丢失很麻烦

**Comment by RiTian96** [comment]
除一直没有的中概互联50（006327）外，原有的纳指100（040046）也无法添加了

**Comment by x2rr** [comment]
请先确定是否能正常访问google，是否登录了同一个账号，数据是通过google账号同步的

**Comment by x2rr** [comment]
> 除一直没有的中概互联50（006327）外，原有的纳指100（040046）也无法添加了

取自天天基金网：当前产品为QDII基金，投资于境外市场，暂无净值估算数据。

**Comment by CaoShenZhou** [comment]
> 请先确定是否能正常访问google，是否登录了同一个账号，数据是通过google账号同步的

可以谷歌,没动过,其他人也出现了这种问题

**Comment by javaygq** [comment]
谷歌账户没有问题，也能登录，另外添加基金提示成功，但是没有显示出来

**Comment by codersellingpizza** [comment]
总收益今天开始一直是0 请问啥情况？

**Comment by RaymondXiao1991** [comment]
只显示了8条，添加8条之外的基金又报已存在，但就是找不着。

**Comment by x2rr** [comment]
> 只显示了8条，添加8条之外的基金又报已存在，但就是找不着。

请提供一下出问题的基金代码

**Comment by RaymondXiao1991** [comment]
> 问题

比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。

**Comment by RiTian96** [comment]
> > 除一直没有的中概互联50（006327）外，原有的纳指100（040046）也无法添加了
> 
> 取自天天基金网：当前产品为QDII基金，投资于境外市场，暂无净值估算数据。

原来海外还有个昨日净值的，所以是天天基金改了？

**Comment by RaymondXiao1991** [comment]
> > 问题
> 
> 比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。

![image](https://user-images.githubusercontent.com/8736080/90466610-ceb1b580-e144-11ea-9419-4eda8a97a2e1.png)
![image](https://user-images.githubusercontent.com/8736080/90466648-e5580c80-e144-11ea-9038-ed53759d745d.png)

**Comment by x2rr** [comment]
> > 问题
> 
> 比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。

是否为最新版本1.5.6，最新版测试未发现问题

**Comment by RaymondXiao1991** [comment]
> > > 问题
> > 
> > 
> > 比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。
> 
> 是否为最新版本1.5.6，最新版测试未发现问题
![image](https://user-images.githubusercontent.com/8736080/90466831-467fe000-e145-11ea-94ab-1db0ebad9246.png)

**Comment by javaygq** [comment]
> > > 问题
> > 
> > 
> > 比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。
> 
> 是否为最新版本1.5.6，最新版测试未发现问题
![image](https://user-images.githubusercontent.com/34884079/90466947-9199f300-e145-11ea-8a03-e3374262cceb.png)

**Comment by RaymondXiao1991** [comment]
> > > > 问题
> > > 
> > > 
> > > 比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。
> > 
> > 
> > 是否为最新版本1.5.6，最新版测试未发现问题
> > ![image](https://user-images.githubusercontent.com/8736080/90466831-467fe000-e145-11ea-94ab-1db0ebad9246.png)

浏览器是Edge。

**Comment by yi-Xu-0100** [comment]
> > > 问题
> > 
> > 
> > 比如说代码003494，我之前是添加过的。昨天开始显示不正常，003494不在8条之列，但我在设置里添加003494弹出的提示是已经添加过的。
> 
> 是否为最新版本1.5.6，最新版测试未发现问题

使用的是最新版，以前添加过大概 10 个左右，今天看了下就剩 1 个了。没有对该插件的任何内容做过修改。

角标能够正常变化，参考的是我以前设置的基金：005918 天弘沪深300ETF联接C
无法再次添加，但是页面没有相关的显示。

**Comment by codersellingpizza** [comment]
有人和我一样总收益是0么

**Comment by CaoShenZhou** [comment]
> 有人和我一样总收益是0么

我

**Comment by alpha2016** [comment]
我也是，一直有 10个左右的基金，今天就剩下两个了，什么情况

**Comment by CaoShenZhou** [comment]
> 我也是，一直有 10个左右的基金，今天就剩下两个了，什么情况

我们差不多

**Comment by alpha2016** [comment]
> > 我也是，一直有 10个左右的基金，今天就剩下两个了，什么情况
> 
> 我们差不多

真的是什么都没改，好像浏览器历史都没清理

**Comment by CaoShenZhou** [comment]
> > > 我也是，一直有 10个左右的基金，今天就剩下两个了，什么情况
> > 
> > 
> > 我们差不多
> 
> 真的是什么都没改，好像浏览器历史都没清理

也不知道啥情况,作者还没恢复这个问题,等修复吧

**Comment by oupc** [comment]
我还以为就我一个人出了这个问题

**Comment by AndsteLyc** [comment]
临时解决方案(**清除基金配置信息，重新添加配置**)：
1. 点图标，弹出基金页面
2. 在页面上右键，选择检查
3. 在弹出的控制面板切换到Console选项卡
4. 在下面的命令行输入
    ```chrome.storage.sync.remove(["RealtimeFundcode", "fundListM", "showAmount", "showGains", "fundList"])```
紧接着给他来一个强有力的回车
5. 重新添加基金代码

**Comment by Qixingchen** [comment]
似乎和添加了 QDII 基金有关.清空后重新添加,所有 QDII 基金都无法添加 例如 486002 486001 000988 096001

**Comment by wang0618** [comment]
感觉像是基金列表中从第一个出现错误的基金开始之后的都无法显示了，希望作者加一下异常catch，对于无法查询的基金也进行一下提示

**Comment by x2rr** [comment]
现有接口无法获取某些基金信息，已做特殊处理，不再影响其他基金，等后续寻找其他合适接口
