### ISSUE TITLE
添加的部分基金无法显示

### ISSUE THREAD

**Issue by hy04** [x2rr/funds#36]
你好！最近这一周 有很多自选的基金都显示不出来，请问这是什么原因呢？是接口的问题吗？有什么办法修复呢？感谢！

**Comment by daili365x24** [comment]
我这里也是，只显示前六个，后面的都不显示了，重新添加提升已经添加过。

**Comment by x2rr** [comment]
现有接口无法获取某些基金信息，已做特殊处理，不再影响其他基金，等后续寻找其他合适接口
