### ISSUE TITLE
000369这个基金显示不出来

### ISSUE THREAD

**Issue by 346570643** [x2rr/funds#39]
![image](https://user-images.githubusercontent.com/45865524/91372058-39e64080-e845-11ea-8c28-7c36fde0b23d.png)

**Comment by yi-Xu-0100** [comment]
看说明

![image](https://user-images.githubusercontent.com/25523606/91372311-e7595400-e845-11ea-8231-d0accd870cc3.png)

**Comment by x2rr** [comment]
目前的接口无法获取这些基金的详情，等后续寻找其他合适接口
