### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by fonding** [x2rr/funds#4]
首先感谢作者的贡献，这个插件炒鸡好用。

我在美国东部时区。我注意到这个插件的数据更新时间是以电脑时间为准的，这样就与国内有12小时时差。国内股市开盘的时候不会自动更新。请问能否让它自动转换时区。

**Comment by x2rr** [comment]
> 首先感谢作者的贡献，这个插件炒鸡好用。
> 
> 我在美国东部时区。我注意到这个插件的数据更新时间是以电脑时间为准的，这样就与国内有12小时时差。国内股市开盘的时候不会自动更新。请问能否让它自动转换时区。

下个版本修复
