### ISSUE TITLE
为何我下载不到1.7.1的版本   

### ISSUE THREAD

**Issue by xiaotianwl** [x2rr/funds#43]
为何我下载不到1.7.1的版本    但是我看到了迭代日志里面有 1.7.1更新的内容了！

**Comment by x2rr** [comment]
> 为何我下载不到1.7.1的版本 但是我看到了迭代日志里面有 1.7.1更新的内容了！

因为商店还在审核，等一会儿审核通过就可以了

**Comment by xiaotianwl** [comment]
看到了   20分钟前更新  火狐浏览器已经通过了     感谢大佬的插件
