### ISSUE TITLE
持有收益和持有收益率 好像没有统计进去

### ISSUE THREAD

**Issue by xiaotianwl** [x2rr/funds#45]
持有收益和持有收益率 好像没有统计进去  
 希望大佬有空了看看

**Comment by x2rr** [comment]
> 持有收益和持有收益率 好像没有统计进去
> 希望大佬有空了看看

需要添加持仓成本价，才能计算持有收益

**Comment by xiaotianwl** [comment]
好嘞   感谢 感谢

**Comment by Ice-Castellan** [comment]
为什么我无法添加持仓的信息，之前还好好的，换了电脑后就无法添加持仓信息了

**Comment by x2rr** [comment]
> 为什么我无法添加持仓的信息，之前还好好的，换了电脑后就无法添加持仓信息了

看一下设置里是否打开了"显示持有收益"

**Comment by Ice-Castellan** [comment]
哇，可以了可以了，之前咋都没找到\尴尬
谢谢大佬，回复的好快\赞
