### ISSUE TITLE
只有预估净值

### ISSUE THREAD

**Issue by iOSleep** [x2rr/funds#5]
可以考虑改成某宝那样，有当天的净值用净值，没有用估值

**Comment by iOSleep** [comment]
可以 15 点后可以通过这个链接来尝试获取当日的净值

[http://fund.eastmoney.com/f10/F10DataApi.aspx?type=lsjz&code=320007&page=1&per=20&sdate=2020-07-10&edate=2020-07-10](http://fund.eastmoney.com/f10/F10DataApi.aspx?type=lsjz&code=320007&page=1&per=20&sdate=2020-07-10&edate=2020-07-10)

**Comment by x2rr** [comment]
> 可以考虑改成某宝那样，有当天的净值用净值，没有用估值

后续考虑加入

**Comment by x2rr** [comment]
最新版已支持
