### ISSUE TITLE
部分基金获取不到，无法计算金额

### ISSUE THREAD

**Issue by yi-Xu-0100** [x2rr/funds#52]
![image](https://user-images.githubusercontent.com/25523606/93756861-5b65fc80-fc38-11ea-8e67-3ec52a51d946.png)

如图，部分基金获取不到信息，我也没有设置持有份额，会计算有误，是否对这些值设为 0 ，以完成计算。

**Comment by x2rr** [comment]
> ![image](https://user-images.githubusercontent.com/25523606/93756861-5b65fc80-fc38-11ea-8e67-3ec52a51d946.png)
> 
> 如图，部分基金获取不到信息，我也没有设置持有份额，会计算有误，是否对这些值设为 0 ，以完成计算。

已发现问题，稍后更新

**Comment by yi-Xu-0100** [comment]
最新版 v2.0.2 验证修复完成~
