### ISSUE TITLE
你好，最新版本，图片上的数字有几率出现NaN

### ISSUE THREAD

**Issue by 18121259693** [x2rr/funds#54]
如题，特别关注的是 161726 “招商国证生物医药指数分级”
过一段时，图标就变红底白字的NaN
然后点开就好了

![image](https://user-images.githubusercontent.com/34698305/93837614-690f9680-fcb9-11ea-8bba-0c85e89725c0.png)

**Comment by x2rr** [comment]
> 如题，特别关注的是 161726 “招商国证生物医药指数分级”
> 过一段时，图标就变红底白字的NaN
> 然后点开就好了
> 
> ![image](https://user-images.githubusercontent.com/34698305/93837614-690f9680-fcb9-11ea-8bba-0c85e89725c0.png)

版本号是2.0.2吗？应该修复了这个问题

**Comment by 18121259693** [comment]
你好，是2.0.2，并且我这里是今天早上才开始这现象的
![image](https://user-images.githubusercontent.com/34698305/93840743-0d96d600-fcc4-11ea-871e-b4a828a002f4.png)

**Comment by x2rr** [comment]
> 你好，是2.0.2，并且我这里是今天早上才开始这现象的
> ![image](https://user-images.githubusercontent.com/34698305/93840743-0d96d600-fcc4-11ea-871e-b4a828a002f4.png)

在改了，一会儿再发一版

**Comment by x2rr** [comment]
2.0.4应该解决了，看看还有这个问题吗
