### ISSUE TITLE
更新日志无法显示，无法进行后续操作。

### ISSUE THREAD

**Issue by coppyC** [x2rr/funds#57]
抓了下包，发现更新日志的接口是 https://x2rr.github.io/funds/src/common/changeLog.json

但是由于天朝特色， github.io 时不时被 Q，导致界面一直卡在更新日志上，无法进行后续操作。

建议接口请求失败后，关闭更新日志，不然什么操作也做不了。

希望能理解下不能随时 fq 的普通用户。

**Comment by x2rr** [comment]
之前有一个版本，无法关闭，最新版已正常，可以点击弹窗最下方的确定按钮。更新日志只有在更新后第一次打开时弹出，点击确定后不再弹出。

**Comment by coppyC** [comment]
注意到了。谢谢
