### ISSUE TITLE
【累计收益】统计截止日期异常

### ISSUE THREAD

**Issue by ren-p** [x2rr/funds#58]
今天是10月12日。但每只基金的【累计收益】的统计截止日期都不对，有的是7月8日，有的是7月6日。
【单位净值】等其他tab下的统计截止日期都正常。

![image](https://user-images.githubusercontent.com/33214126/95701960-8b278380-0c7d-11eb-9f8d-6577dc486299.png)
![image](https://user-images.githubusercontent.com/33214126/95702088-e8bbd000-0c7d-11eb-9ba0-79d9b4f3afd8.png)
![image](https://user-images.githubusercontent.com/33214126/95702230-523bde80-0c7e-11eb-87cd-dbc72c7e9d38.png)

**Comment by x2rr** [comment]
最新版已解决
