### ISSUE TITLE
[Bug]Chrome中添加新基金输入框无光标展示并且输入内容不会实时展示

### ISSUE THREAD

**Issue by liulinru13** [x2rr/funds#6]
【问题描述】
打开编辑的弹窗后，新增基金的输入框中，光标无展示，输入框在输入过程中不会实时展示文本内容
需要一次性输入完毕后，点确定看结果来验证输入是否正确

【环境】
Chrome浏览器版本：85.0.4181.8
操作系统 MacOS 10.15.5

**Comment by x2rr** [comment]
> 【问题描述】
> 打开编辑的弹窗后，新增基金的输入框中，光标无展示，输入框在输入过程中不会实时展示文本内容
> 需要一次性输入完毕后，点确定看结果来验证输入是否正确
> 
> 【环境】
> Chrome浏览器版本：85.0.4181.8
> 操作系统 MacOS 10.15.5

经测试，该问题可能为macOS与Chrome扩展之间的兼容性问题，并且只在扩展显示器上出现，在主显示器上正常，建议在主显示器上进行输入操作

**Comment by liulinru13** [comment]
> > 【问题描述】
> > 打开编辑的弹窗后，新增基金的输入框中，光标无展示，输入框在输入过程中不会实时展示文本内容
> > 需要一次性输入完毕后，点确定看结果来验证输入是否正确
> > 【环境】
> > Chrome浏览器版本：85.0.4181.8
> > 操作系统 MacOS 10.15.5
> 
> 经测试，该问题可能为macOS与Chrome扩展之间的兼容性问题，并且只在扩展显示器上出现，在主显示器上正常，建议在主显示器上进行输入操作

确实如此，感谢回复
