### ISSUE TITLE
超过50个基金后，后面添加的基金不会显示

### ISSUE THREAD

**Issue by JackieCheung** [x2rr/funds#60]

**Comment by JackieCheung** [comment]
@x2rr

**Comment by jq384044342** [comment]
> 
> 
> @x2rr

你是来测试的吗。。。

**Comment by JackieCheung** [comment]
> > @x2rr
> 
> 你是来测试的吗。。。

哈哈 不是 纯属是关注的基金太多了 😄

**Comment by jq384044342** [comment]
> 
> 
> > > @x2rr
> > 
> > 
> > 你是来测试的吗。。。
> 
> 哈哈 不是 纯属是关注的基金太多了 smile

哈哈哈，厉害哦，方便分享下关注的基金吗

**Comment by xuzhonglin** [comment]
这是因为插件调用的接口限制每页大小50

**Comment by x2rr** [comment]
最新版已改为200个
