### ISSUE TITLE
eastmoney的域名国内无法访问

### ISSUE THREAD

**Issue by longzhiwuing** [x2rr/funds#64]
fundmobapi.eastmoney.com和push2.eastmoney.com

是东方财富的域名挂了么？现在插件一直在转圈，无法使用啊。。。

![image](https://user-images.githubusercontent.com/5849090/99238507-c563e200-2834-11eb-853a-65df0fe959ee.png)

![image](https://user-images.githubusercontent.com/5849090/99238521-c85ed280-2834-11eb-89ed-7f17a30cb026.png)

**Comment by x2rr** [comment]
个人网络原因，请排除网络服务商是否屏蔽该域名
