### ISSUE TITLE
基金净值、收益率纵坐标值显示错误

### ISSUE THREAD

**Issue by stardance** [x2rr/funds#69]
基金的历史净值，累积收益纵坐标值不对：
![image](https://user-images.githubusercontent.com/19811097/100198356-b0730700-2f36-11eb-88f8-a2edbfdd0b1e.png)
![image](https://user-images.githubusercontent.com/19811097/100198111-5a9e5f00-2f36-11eb-9ac5-469cdca9e1a4.png)
净值：3年怎么可能就9个点涨幅
收益率：100%的收益率，但是百位1被遮住了，只显示00%
还望大佬修正

**Comment by x2rr** [comment]
最新版已修复
