### ISSUE TITLE
大佬能不能搞个小程序

### ISSUE THREAD

**Issue by xuzhonglin** [x2rr/funds#78]
如题，下班了，手机上也方便查看收益

**Comment by Germxu** [comment]
都用手机了为什么还要在这看, 这毕竟是第三方数据, 没有官方的准, 在哪买的基金去哪看啊

**Comment by x2rr** [comment]
计划出一个简易版的小程序，方便下班后查看

**Comment by x2rr** [comment]
已上线，小程序名称：韭菜计算助手
