### ISSUE TITLE
估算收益计算错误

### ISSUE THREAD

**Issue by JackieCheung** [x2rr/funds#84]
如下：

基金名称                                  |   估算净值   |  持有额   |  涨跌幅  |  估算收益  | 更新时间
中欧品质消费股票C(005621)   |    2.0462      |  1,363.17 |  -0.31%  |  -146.03    | 12-24 09:31

**Comment by JackieCheung** [comment]
![image](https://user-images.githubusercontent.com/31252046/103048869-fcaf7680-45ca-11eb-99de-86317cf1370e.png)

**Comment by x2rr** [comment]
经验证，该基金分红折算了，所以导致持有变少，请查看对应购买平台
