### ISSUE TITLE
行情中心资金流向tab有bug

### ISSUE THREAD

**Issue by kfqkfy** [x2rr/funds#87]
点开行业板块资金流向tab页，最左边的柱子没显示，需要拖一下底下的range条拖到最左才显示最左边的柱子

![image](https://user-images.githubusercontent.com/2724562/103253029-5f818300-49ba-11eb-85ab-636dda74c83c.png)

![image](https://user-images.githubusercontent.com/2724562/103253037-690aeb00-49ba-11eb-856c-64b0a6a2f7d9.png)

**Comment by x2rr** [comment]
最新版已解决
