### ISSUE TITLE
估算收益和涨跌幅不一致

### ISSUE THREAD

**Issue by chenn1u** [x2rr/funds#98]
只有这个基金出了问题
![ETp9OM4](https://i.imgur.com/ETp9OM4.png)

**Comment by lliuz** [comment]
same problem
![image](https://user-images.githubusercontent.com/20420011/104875696-e2ca3f00-5990-11eb-93a5-e95f25c819a0.png)

**Comment by overxue** [comment]
@lliuz @chenn1u 基金在产生分红，会出现估算收益跟涨跌幅不一样
